# Generated by Django 3.1.3 on 2020-12-07 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserService', '0001_initial'),
        ('CommodityService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0, verbose_name='订单金额')),
                ('order_state', models.CharField(choices=[('paying', '待付款'), ('paid', '已付款'), ('refunded', '已退款'), ('cancelled', '已取消')], max_length=30, verbose_name='订单状态')),
                ('order_time', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='UserService.user', verbose_name='买家')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommodityService.commodity', verbose_name='商品')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='UserService.user', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('seller_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_quality', models.IntegerField(default=0, verbose_name='商品质量')),
                ('deal_speed', models.IntegerField(default=0, verbose_name='交易速度')),
                ('seller_attitude', models.IntegerField(default=0, verbose_name='卖家态度')),
                ('comment', models.TextField(default='', max_length=200, verbose_name='文字评价')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='评价时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderService.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '对卖家的评价',
                'verbose_name_plural': '对卖家的评价',
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0, verbose_name='支付金额')),
                ('payment_type', models.CharField(choices=[('B2P', '买家付款给平台'), ('P2S', '平台付款给卖家'), ('S2B', '卖家退款给买家'), ('P2B', '平台退款给买家')], max_length=30, verbose_name='支付类型')),
                ('payment_platform', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信')], max_length=20, verbose_name='支付平台')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderService.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
            },
        ),
        migrations.CreateModel(
            name='BuyerReview',
            fields=[
                ('buyer_review_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, verbose_name='综合评分')),
                ('comment', models.TextField(default='', max_length=200, verbose_name='文字评价')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='评价时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderService.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '对买家的评价',
                'verbose_name_plural': '对买家的评价',
            },
        ),
    ]
