# Generated by Django 3.1.3 on 2020-12-07 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_content', models.TextField(default='', max_length=200, verbose_name='消息内容')),
                ('message_state', models.CharField(choices=[('read', '已读'), ('unread', '未读')], max_length=20, verbose_name='消息状态')),
                ('send_time', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('receive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='UserService.user', verbose_name='目标用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='UserService.user', verbose_name='源用户')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
            },
        ),
    ]
