# Generated by Django 3.1.3 on 2021-01-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommunicationService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='if_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_state',
            field=models.CharField(choices=[('read', '已读'), ('unread', '未读')], default='未读', max_length=20, verbose_name='消息状态'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发送时间'),
        ),
    ]
