# Generated by Django 3.1.3 on 2020-12-07 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrderService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundApplication',
            fields=[
                ('refund_id', models.AutoField(primary_key=True, serialize=False)),
                ('refund_state', models.CharField(choices=[('TO_BE_REVIEWED', '待审核'), ('APPROVED', '同意退款'), ('REJECTED', '拒绝退款')], default='TO_BE_REVIEWED', max_length=20)),
                ('refund_apply_time', models.DateTimeField(auto_now_add=True)),
                ('refund_reason', models.TextField()),
                ('refund_time', models.DateTimeField(blank=True)),
                ('if_delete', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderService.order')),
            ],
        ),
    ]
