# Generated by Django 3.1.3 on 2020-12-07 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserService', '0001_initial'),
        ('CommodityService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites_detail',
            fields=[
                ('favourites_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('collect_time', models.DateTimeField(blank=True, null=True, verbose_name='收藏时间')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommodityService.commodity', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserService.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏夹明细',
                'verbose_name_plural': '收藏夹明细',
            },
        ),
    ]
