# Generated by Django 3.1.3 on 2021-01-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FavouritesService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites_detail',
            name='if_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favourites_detail',
            name='collect_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='收藏时间'),
        ),
    ]
