# Generated by Django 3.1.3 on 2020-12-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='')),
                ('real_name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('MALE', '男性'), ('FEMALE', '女性')], max_length=6)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('account_state', models.CharField(choices=[('AVAILABLE', '可用'), ('DISABLE', '禁用')], max_length=20)),
                ('credit_score', models.IntegerField()),
                ('online_state', models.CharField(choices=[('ONLINE', '在线'), ('OFFLINE', '离线')], max_length=20)),
                ('identity', models.CharField(choices=[('USER', '用户'), ('ADMINISTRATOR', '管理员')], default='USER', max_length=20)),
            ],
        ),
    ]
