# Generated by Django 3.1.3 on 2021-01-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserService', '0003_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='if_delete',
            field=models.BooleanField(default=False),
        ),
    ]
